theme: jekyll-theme-minimal
title: Yaphet's Homepage
description: I am digging a pit!
logo: /assets/img/cat.jpg
show_downloads: false
google_analytics: UA-120749243-1
exclude: ["README.md","License.md"]
